### ISSUE TITLE
Python Opencenus Trace ID and Span ID in azure monitor

### ISSUE THREAD

**Issue by abhishekkumaresan** [census-ecosystem/opencensus-python-extensions-azure#8]
I am trying to add traceId and spanId to logs in azure functions in python, following https://docs.microsoft.com/en-us/azure/azure-monitor/app/correlation#log-correlation in Azure documentation

traceId and spanId is added to log statements in local development using VS Code but I am not able to see the same traceId and spanId in azure monitor,
``
I followed https://docs.microsoft.com/en-us/azure/azure-monitor/app/opencensus-python#logs section of the documentation to add AzureLogHandler but still things don't seem to work

I want to be able to query the logs in Azure Application insights using the traceId and spanId What is missing in my code so traceId and spanId is not logged in azure monitor

Below is my code to configure logs in python

```
def logger_and_tracer(name):
    config_integration.trace_integrations(["logging", "requests"])
    tracer = Tracer(sampler=AlwaysOnSampler())
    formatter = logging.Formatter(
        "fileName=%(filename)s functionName=%(funcName)s traceId=%(traceId)s spanId=%(spanId)s %(message)s"
    )
    logger = logging.getLogger(name)
    azure_logger = AzureLogHandler()
    syslog = logging.StreamHandler()
    azure_logger.addFilter(CustomDimensionsFilter(default_log_items))
    syslog.addFilter(CustomDimensionsFilter(default_log_items))

    azure_logger.setFormatter(formatter)
    syslog.setFormatter(formatter)

    logger.setLevel(logging.DEBUG)

    logger.addHandler(syslog)
    logger.addHandler(azure_logger)

    return (logger, tracer)


```

**Comment by lzchen** [comment]
@abhishekkumaresan 
Just to clarify, you are getting the log telemetry in the "traces" table in Azure monitor but the `operation_id` and `parent_operation_id` fields are 0s correct? Could you provide a screenshot of this?

Can you also show how you are calling `logger_and_tracer()` to instantiate your logger, where you are calling `logger.warning...` and also what the logs look like in "local development using VS Code ".

**Comment by abhishekkumaresan** [comment]
Hi @lzchen 

I am getting the traceId and spanId in local development
The blue line above the Yellow one, I am getting traceId and spanId with other items
![local_azure_functions](https://user-images.githubusercontent.com/10154985/149079606-714dcd4a-ec82-40f2-91c8-93cb1bc51244.png)


 but I am not getting the same in Azure monitor or Application Insights

![Web capture_12-1-2022_122653_portal azure com](https://user-images.githubusercontent.com/10154985/149079940-e0ed6074-5b6d-473c-8e5a-9d2f8269240a.jpeg)



below is the sample HTTP trigger where logger_and_tracer is invoked 


```
def main(req: func.HttpRequest, context: func.Context) -> func.HttpResponse:

    name = "My Name"
    logger, tracer = config.logger_and_tracer(__name__)
    logger.warning("name = {name}".format(name=name))
    if not name:
        try:
            req_body = req.get_json()
        except ValueError:
            pass
        else:
            name = req_body.get("name")

    if name:
        return func.HttpResponse(
            f"Hello, {name}. This HTTP triggered function executed successfully.",
            headers={"trace_id": tracer.get_tracer().trace_id},
        )
    else:
        return func.HttpResponse(
            "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
            headers={"trace_id": tracer.get_tracer().trace_id},
            status_code=200,
        )

```


```
azure-common==1.1.27
azure-core==1.16.0
azure-functions==1.7.2
azure-identity==1.6.0
azure-keyvault-secrets==4.3.0
azure-storage-blob==12.9.0b1
azure-storage-file-datalake==12.5.0b1
opencensus==0.8.0
opencensus-context==0.1.2
opencensus-ext-azure==1.0.8
opencensus-ext-logging==0.1.0
opencensus-ext-requests==0.7.5
opencensus-extension-azure-functions==1.0.0
```

This is my requirements.txt, I feel I am missing somewhere with setup and dependency
Prior to asking here I posted in Stackoverflow https://stackoverflow.com/questions/70636922/python-opencenus-trace-id-and-span-id-in-azure-monitor

I tried even the one in there he is able to see traceId but I am not seeing it 

Thanks

**Comment by lzchen** [comment]
@abhishekkumaresan 
In the example output you pasted, you are getting a value for `traceid` but `spanid` is zeroed out. This mostly means that you are able to get a trace Id from SOME Tracer instance (it is probably the tracer instance that is created from `logger_and_tracer`). The reason why your `spanid` is zeroed out is because you are not encapsulating your logging statement within a span.
Try adding this:

```python
with tracer.span(name='http-operation'):
      logger.warning("name = {name}".format(name=name))
```

This will probably correlate your log messages with the `INTERNAL` span that you generate with the tracer that you've created. Now, what I'm assuming is that you actually want to be correlating your log messages with your AZURE FUNCTIONS CALLS. If that's the case, you shouldn't use an internal tracer, you need to use the tracer that is passed into the context (because this is the tracer that is used to handle azure functions calls telemetry). 

As shown in the stackoverflow answer:

```python
# You must use context.tracer to create spans

    with context.tracer.span("parent"):
    logger.info('Message from HttpTrigger')
    return json.dumps({
    'method': req.method,
    'ctx_func_name': context.function_name,
    'ctx_func_dir': context.function_directory,
    'ctx_invocation_id': context.invocation_id,
    'ctx_trace_context_Traceparent': context.trace_context.Traceparent,
    'ctx_trace_context_Tracestate': context.trace_context.Tracestate,
    })
```

**Comment by abhishekkumaresan** [comment]
@lzchen  Thanks, I get your point, but for me the trace and span information is not getting logged in Application Insights or Azure Monitor 

![local_with_trace](https://user-images.githubusercontent.com/10154985/149205321-6e04f3cd-49cb-4ba9-9e01-ef48178787d8.png)

This is Local Azure functions in VS code here we can see the Span Information but 

![Web capture_13-1-2022_0320_portal azure com](https://user-images.githubusercontent.com/10154985/149205555-6fa57ca8-c3b4-4552-906b-c69d640f1a7d.jpeg)

But here in Azure Monitor it is not logged, bit strange, mostly  I am missing something, not sure what is that

The code for this is 

```
def main(req: func.HttpRequest, context: func.Context):

    OpenCensusExtension.configure()
    config_integration.trace_integrations(["logging"])
    logging.basicConfig(
        format="%(asctime)s traceId=%(traceId)s spanId=%(spanId)s %(message)s"
    )
    tracer = Tracer(sampler=AlwaysOnSampler())
    logger = logging.getLogger(__name__)
    logger.warning("Before the span")
    with tracer.span(name="hello"):
        logger.warning("In the span")
    logger.warning("After the span")

    logger.info("Executing HttpTrigger with OpenCensus extension")

    # You must use context.tracer to create spans

    with context.tracer.span("parent"):
        logger.info("Message from HttpTrigger")
        return json.dumps(
            {
                "method": req.method,
                "ctx_func_name": context.function_name,
                "ctx_func_dir": context.function_directory,
                "ctx_invocation_id": context.invocation_id,
                "ctx_trace_context_Traceparent": context.trace_context.Traceparent,
                "ctx_trace_context_Tracestate": context.trace_context.Tracestate,
            }
        )


```

I have one more question

Will all the log statements have _InvocationId_  in it,  will I get all the log statements of a particular request if I query with 

**where customDimensions['InvocationId'] == '<Request's InvocationID from context>'**

**Comment by lzchen** [comment]
@abhishekkumaresan 
> But here in Azure Monitor it is not logged, bit strange, mostly I am missing something, not sure what is that

I'm not sure if the screenshot you are pasting is the right place to look. The traceId/spanId should be represented by the `operation_id` and `parent_operationId` respectively. Can you paste a screenshot of those fields?

**Comment by abhishekkumaresan** [comment]
@lzchen Yes correct, `context.trace_context.Traceparent`  returns **"00-843355861749b0c7b5454ea3d6f05c2b-fb20540fcea60292-00"**
And the Operation_Id for the request is **843355861749b0c7b5454ea3d6f05c2b**, Now I can match and query for the logs 

previously when I was using `tracer.get_tracer().trace_id` the trace_id was not matching with the Operation_Id, and that is because I was using a internal tracer that I generated 

Thanks for taking the time to explain
